services:
  app:
    image: node:24
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
      - "4173:4173"
    tty: true
    stdin_open: true
    command: sh -c "npm install && npm run dev -- --host"

  api:
    image: node:24
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3001:3001"
    command: sh -c "npx json-server --watch db.json --port 3001 --host 0.0.0.0"
    tty: true
    stdin_open: true